### ISSUE TITLE
How to hook up Real Pit for AIO CC?

### ISSUE THREAD

**Issue by BikeGuy1992** [flyduino/kissfc-firmware#7]
There is no PWM5 pad on the AIO CC FC+ESC that I know of. Is there another way to hook a real pit up to the AIO board?

**Comment by lichtl** [comment]
Please see release notes for 1.3RC39b - MI on SPI1

**Comment by BikeGuy1992** [comment]
Just checked on GitHub, looks good to me. Thanks for the help Carsten.

Zaine (BikeGuy)
